### ISSUE TITLE
100 images limit

### ISSUE THREAD

**Issue by gssci** [impshum/reddit-image-downloader#3]
Thank you so much for this, as it works on google colab for getting an image dataset. 
The script stops after downloading 100 images even if I increase the -i number. 

Is there a way to go over this limit? Thanks again

**Comment by impshum** [comment]
Yeah, I'm pretty sure I can do that.

Have you tried anything interesting yet?

**Comment by impshum** [comment]
Should be OK now. The Reddit API gives a maximum of 1000 posts when the limit is set to ```None```.

https://github.com/impshum/Multithreaded-Reddit-Image-Downloader/commit/ebc153680f282e5f77e18a7004181e10a4d88783
